In [13]:
import pandas as pd
import category_encoders as ce

In [14]:
clothing_list = [
    ['xxs', 'dress'],
    ['xxs', 'skirt'],
    ['xs', 'dress'],
    ['s', 'skirt'],
    ['m', 'dress'],
    ['l', 'shirt'],
    ['s', 'coat'],
    ['m', 'coat'],
    ['xxl', 'shirt'],
    ['l', 'dress']
]

clothing = pd.DataFrame(clothing_list, columns = ['size',  'type'])
clothing

  size   type
0  xxs  dress
1  xxs  skirt
2   xs  dress
3    s  skirt
4    m  dress
5    l  shirt
6    s   coat
7    m   coat
8  xxl  shirt
9    l  dress

In [15]:
#Метод fit_transform устанавливает соответствия для кодирования и преобразовывает данные в соответствие с ними. 
#Затем используем метод concat() для добавления закодированного признака в датафрейм data.
ord_encoder = ce.OrdinalEncoder()
#data_bin = ord_encoder.fit_transform(clothing[['size', 'type']])
data_bin = ord_encoder.fit_transform(clothing['size'])
clothing = pd.concat([clothing, data_bin], axis=1)

clothing

   size   type  size
0   xxs  dress     1
1   xxs  skirt     1
2    xs  dress     2
3     s  skirt     3
4     m  dress     4
5     l  shirt     5
6     s   coat     3
7     m   coat     4
8   xxl  shirt     6
9     l  dress     5

In [16]:
encoder = ce.OneHotEncoder(cols=['type']) # указываем столбец для кодирования
type_bin = encoder.fit_transform(clothing['type'])
clothing = pd.concat([clothing, type_bin], axis=1)

clothing

   size   type  size  type_1  type_2  type_3  type_4
0   xxs  dress     1       1       0       0       0
1   xxs  skirt     1       0       1       0       0
2    xs  dress     2       1       0       0       0
3     s  skirt     3       0       1       0       0
4     m  dress     4       1       0       0       0
5     l  shirt     5       0       0       1       0
6     s   coat     3       0       0       0       1
7     m   coat     4       0       0       0       1
8   xxl  shirt     6       0       0       1       0
9     l  dress     5       1       0       0       0

In [17]:
bin_encoder = ce.BinaryEncoder(cols=['type']) # указываем столбец для кодирования
type_bin = bin_encoder.fit_transform(clothing['type'])
clothing = pd.concat([clothing, type_bin], axis=1)

clothing

   size   type  size  type_1  type_2  type_3  type_4  type_0  type_1  type_2
0   xxs  dress     1       1       0       0       0       0       0       1
1   xxs  skirt     1       0       1       0       0       0       1       0
2    xs  dress     2       1       0       0       0       0       0       1
3     s  skirt     3       0       1       0       0       0       1       0
4     m  dress     4       1       0       0       0       0       0       1
5     l  shirt     5       0       0       1       0       0       1       1
6     s   coat     3       0       0       0       1       1       0       0
7     m   coat     4       0       0       0       1       1       0       0
8   xxl  shirt     6       0       0       1       0       0       1       1
9     l  dress     5       1       0       0       0       0       0       1

In [23]:
list_of_dicts = [
 {'product': 'Product1', 'price': 1200, 'payment_type': 'Mastercard'},
 {'product': 'Product2', 'price': 3600, 'payment_type': 'Visa'},
 {'product': 'Product3', 'price': 7500, 'payment_type': 'Amex'}
]
df = pd.DataFrame(list_of_dicts)

In [24]:
ohe_encoder = ce.OneHotEncoder(cols=['product', 'payment_type'])
data_bin = ohe_encoder.fit_transform(df[['product', 'payment_type']])
df = pd.concat([df, data_bin], axis=1)

df

,product,price,payment_type,product_1,product_2,product_3,payment_type_1,payment_type_2,payment_type_3
0,Product1,1200,Mastercard,1,0,0,1,0,0
1,Product2,3600,Visa,0,1,0,0,1,0
2,Product3,7500,Amex,0,0,1,0,0,1