In [1]:
import pandas as pd

In [2]:
melb_data = pd.read_csv('data/melb_data_fe.csv', sep=',')

In [3]:
melb_df = melb_data.copy()
melb_df.head()

,Suburb,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,Bedroom,...,Longtitude,Regionname,Propertycount,MeanRoomsSquare,AreaRatio,MonthSale,AgeBuilding,WeekdaySale,StreetType,Weekend
0,Abbotsford,2,house,1480000.0,S,Biggin,2016-03-12,2.5,3067,2,...,144.9984,Northern Metropolitan,4019,25.20,-0.231707,3,46,5,St,1
1,Abbotsford,2,house,1035000.0,S,Biggin,2016-04-02,2.5,3067,2,...,144.9934,Northern Metropolitan,4019,15.80,-0.327660,4,116,5,St,1
2,Abbotsford,3,house,1465000.0,SP,Biggin,2017-04-03,2.5,3067,3,...,144.9944,Northern Metropolitan,4019,18.75,0.056338,4,117,0,St,0
3,Abbotsford,3,house,850000.0,PI,Biggin,2017-04-03,2.5,3067,3,...,144.9969,Northern Metropolitan,4019,15.75,0.145455,4,47,0,other,0
4,Abbotsford,4,house,1600000.0,VB,Nelson,2016-04-06,2.5,3067,3,...,144.9941,Northern Metropolitan,4019,17.75,0.083969,4,2,2,St,0

In [27]:
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  object
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  object
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  object
 5   SellerG          13580 non-null  object
 6   Date             13580 non-null  object
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  object
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  object
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  int64
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  int64
 24  StreetType       13580 non-null  object
 25  Weekend          13580 non-null  int64
dtypes: float64(8), int64(10), object(8)
memory usage: 2.7+ MB

In [4]:
melb_df['Date'] = pd.to_datetime(melb_df['Date'])

In [29]:
melb_df['Date'].dt.quarter.value_counts()

3    4873
2    4359
4    2329
1    2019
Name: Date, dtype: int64

In [5]:
cols_to_exclude = ['Date', 'Rooms', 'Bedroom', 'Bathroom', 'Car'] # список столбцов, которые мы не берём во внимание
max_unique_count = 150 # задаём максимальное число уникальных категорий
for col in melb_df.columns: # цикл по именам столбцов
    if melb_df[col].nunique() < max_unique_count and col not in cols_to_exclude: # проверяем условие
        melb_df[col] = melb_df[col].astype('category') # преобразуем тип столбца
melb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13580 entries, 0 to 13579
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Suburb           13580 non-null  category
 1   Rooms            13580 non-null  int64
 2   Type             13580 non-null  category
 3   Price            13580 non-null  float64
 4   Method           13580 non-null  category
 5   SellerG          13580 non-null  category
 6   Date             13580 non-null  datetime64[ns]
 7   Distance         13580 non-null  float64
 8   Postcode         13580 non-null  int64
 9   Bedroom          13580 non-null  int64
 10  Bathroom         13580 non-null  int64
 11  Car              13580 non-null  int64
 12  Landsize         13580 non-null  float64
 13  BuildingArea     13580 non-null  float64
 14  CouncilArea      12211 non-null  category
 15  Lattitude        13580 non-null  float64
 16  Longtitude       13580 non-null  float64
 17  Regionname       13580 non-null  category
 18  Propertycount    13580 non-null  int64
 19  MeanRoomsSquare  13580 non-null  float64
 20  AreaRatio        13580 non-null  float64
 21  MonthSale        13580 non-null  category
 22  AgeBuilding      13580 non-null  int64
 23  WeekdaySale      13580 non-null  category
 24  StreetType       13580 non-null  category
 25  Weekend          13580 non-null  category
dtypes: category(10), datetime64[ns](1), float64(8), int64(7)
memory usage: 1.8 MB

In [13]:
mask1 = melb_df['AreaRatio'] < -0.8
mask2 = melb_df['Type'] == 'townhouse'
mask3 = melb_df['SellerG'] == 'McGrath'
melb_df[mask1 & mask2 & mask3].sort_values(
    by=['Date', 'AreaRatio'],
    ascending=[True, False],
    ignore_index=True
).loc[:, ['Date', 'AreaRatio']]

        Date  AreaRatio
0 2016-07-26  -0.974922
1 2016-09-24  -0.971831
2 2016-11-27  -0.953608
3 2016-12-11  -0.945946
4 2017-08-04  -0.947368
5 2017-08-04  -0.970874

In [31]:
building_area_1558 = round(
    melb_df.sort_values(
        by='AreaRatio',
        ascending=False,
        ignore_index=True
    )
    .loc[1158, 'BuildingArea'],
    0
)
building_area_1558

49.0

In [37]:
mask_type = melb_df['Type'] == 'townhouse'
mask_rooms = melb_df['Rooms'] > 2
melb_df[mask_type & mask_rooms].sort_values(
    by=['Rooms', 'MeanRoomsSquare'],
    ascending=[True, False],
    ignore_index=True
).loc[18, :]

Suburb                     Brighton East
Rooms                                  3
Type                           townhouse
Price                          1300000.0
Method                                PI
SellerG                           Buxton
Date                 2016-09-17 00:00:00
Distance                            10.7
Postcode                            3187
Bedroom                                3
Bathroom                               2
Car                                    2
Landsize                           337.0
BuildingArea                       222.0
CouncilArea                      Bayside
Lattitude                       -37.9196
Longtitude                      145.0205
Regionname         Southern Metropolitan
Propertycount                       6938
MeanRoomsSquare                    27.75
AreaRatio                      -0.205725
MonthSale                              9
AgeBuilding                           16
WeekdaySale                            5
StreetType                            St
Weekend                                1
Name: 18, dtype: object

In [6]:
melb_df.groupby('Rooms')['Price'].mean()

Rooms
1     4.338245e+05
2     7.750812e+05
3     1.076081e+06
4     1.445282e+06
5     1.870260e+06
6     1.849366e+06
7     1.920700e+06
8     1.602750e+06
10    9.000000e+05
Name: Price, dtype: float64

In [7]:
melb_df.groupby('Regionname')['Lattitude'].std()

Regionname
Eastern Metropolitan          0.047890
Eastern Victoria              0.147067
Northern Metropolitan         0.049639
Northern Victoria             0.084455
South-Eastern Metropolitan    0.073411
Southern Metropolitan         0.043080
Western Metropolitan          0.051251
Western Victoria              0.011579
Name: Lattitude, dtype: float64

In [14]:
mask_date = (melb_df['Date'] >= '2017-05-01') & (melb_df['Date'] <= '2017-09-01') 
melb_df[mask_date].groupby('SellerG')['Price'].sum().sort_values(ascending=True)

SellerG
LITTLE             2742000.0
Cayzer             4439000.0
Burnham            4550500.0
Moonee             7328000.0
Thomson            8332000.0
Bells              8656000.0
Alexkarbon        10985000.0
McDonald          14637500.0
Rendina           15422276.0
Nick              16890000.0
Douglas           18341000.0
Buckingham        19033000.0
C21               19515000.0
Eview             19791500.0
Collins           20217000.0
Philip            22051800.0
Chisholm          23225000.0
Williams          23297000.0
Love              23365500.0
Purplebricks      23401000.0
O'Brien           23855508.0
HAR               25568000.0
Village           26473000.0
RW                29261000.0
Raine             30687700.0
Stockdale         35409800.0
Sweeney           36882750.0
Gary              39138400.0
Hodges            43231000.0
YPA               46354350.0
Miles             47582000.0
Kay               48569500.0
RT                50498000.0
Brad              55955000.0
Jas               59281600.0
Harcourts         68720250.0
McGrath           78386500.0
Greg              85621000.0
Woodards          85977500.0
Noel              88129800.0
Fletchers        108847700.0
Biggin           110429500.0
Buxton           219104000.0
Ray              249572986.0
Marshall         253957888.0
hockingstuart    282834310.0
Barry            296723050.0
other            365038432.0
Nelson           379767500.0
Jellis           414121833.0
Name: Price, dtype: float64

In [15]:
melb_df.pivot_table(
    values='BuildingArea',
    index='Rooms',
    columns='Type',
    aggfunc='median',
    fill_value=0
)

Type   house  townhouse   unit
Rooms
1      126.0       88.0   69.5
2      126.0      114.0  110.0
3      126.0      126.0  126.0
4      141.0      159.5  126.0
5      177.0      152.0    0.0
6      126.0        0.0  171.0
7      216.5        0.0    0.0
8      126.0        0.0  126.0
10     126.0        0.0    0.0

In [19]:
melb_df.pivot_table(
    values='Price',
    index='SellerG',
    columns='Type',
    aggfunc='median',
    fill_value=0
).sort_values(by='unit', ascending=False)

Type             house  townhouse    unit
SellerG
Nick           2025000     780000  900000
Marshall       1975000    1408500  715000
Cayzer         1505000    1450000  707500
Kay            2220000    1365000  695000
Noel           1400500     990000  693250
Buxton         1323750    1030000  670000
Fletchers      1390000    1238000  653000
Chisholm       1520000     950000  640000
Philip         1035000     701000  636000
RT             1640000    1400000  630000
C21             836500     768750  625500
RW              870000     630500  625500
Moonee          806000     715000  622000
O'Brien         737504     430000  618500
Hodges         1500000    1105000  605500
Eview           760000     597500  602000
Woodards       1261000     865500  600000
Collins        1566500     930000  592000
Jellis         1505000    1052000  591750
Purplebricks    810000     927500  582500
Williams       1161000     735000  577000
hockingstuart  1055000     935000  566000
Alexkarbon     1036250     935000  560000
Miles          1090000     721500  555000
Buckingham      830000     820000  553000
Gary           1370000     993500  550000
Biggin         1151750     675000  548000
Greg           1330000     900000  547500
McGrath        1250000     810000  542500
other           901000     840500  535000
Nelson         1055000     730000  530000
HAR             695000          0  518000
McDonald       1242500          0  502500
Barry           830000     727500  502000
Harcourts       740000     653750  500000
Ray             900000     650000  497500
Thomson        1177000     500000  495000
Douglas         684000     500000  494500
Brad            875000     700000  465000
Rendina        1190000     750000  459000
Bells           692500     430500  457500
Jas             935000     699000  455000
Raine           745000     608000  447500
LITTLE          970000     800000  447000
YPA             596250     498500  443500
Love            780000     846000  440000
Village         973500     727500  420000
Stockdale       715500     550000  410000
Sweeney         850000     728000  381000
Burnham         922500          0  305000